### ISSUE TITLE
Q: Action vs. CLI

### ISSUE THREAD

**Issue by aleks-ivanov** [docker/login-action#102]
I was wondering about the warning that the docker CLI gives when logging in:

```
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json
```

How does the action handle it ?
Does the action do the exact same thing as the CLI and just basically masks the warning or does it do the login another way ?

**Comment by crazy-max** [comment]
@aleks-ivanov 

> just basically masks the warning

Yes that's it, see https://github.com/docker/login-action/issues/30 for more info and support of `pass` cred helper.

**Comment by eine** [comment]
Ref: #25
