### ISSUE TITLE
buildx doesn't work with GitHub Package Docker registry

### ISSUE THREAD

**Issue by docwhat** [docker/login-action#11]
> The GitHub Packages Docker registry will be superseded by GitHub Container Registry.

The package registry will never support multi-arch image manifests.   The container registry (ghcr.io) does.

`buildx` pushes multi-arch image manifests, even when using a single architecture.  I don't think this can be turned off.

`docker/build-push-action@v2` uses `buildx`.   Therefore, I don't think it is necessary to have an example for the package registry.  Though a comment mentioning why might be nice.  Possibly with a link to the [migration guide](https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images)

**Comment by crazy-max** [comment]
@docwhat 

> > The GitHub Packages Docker registry will be superseded by GitHub Container Registry.
> 
> The package registry will never support multi-arch image manifests. The container registry (ghcr.io) does.
> 
> `buildx` pushes multi-arch image manifests, even when using a single architecture. I don't think this can be turned off.
> 
> `docker/build-push-action@v2` uses `buildx`. Therefore, I don't think it is necessary to have an example for the package registry. Though a comment mentioning why might be nice. Possibly with a link to the [migration guide](https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images)

First of all, this action only handles login against a registry and does not concern `buildx`.

If no platform is defined, the one detected through your system will be used but it will not produce a manifest list like `application/vnd.docker.distribution.manifest.list.v2+json` but `application/vnd.docker.distribution.manifest.v2+json` so `buildx` will be able to push to the GitHub Package Registry.

**Comment by docwhat** [comment]
1. Yeah, I know, but it was written in conjunction with and for the `build-push-action`.
2. If you say so.  In practice, my tests show that the `build-push-action` is getting a 403 when using the GHPR (with no useful error message) and it works fine for the GHCR.
