### ISSUE TITLE
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')

### ISSUE THREAD

**Issue by peterzernia** [docker/login-action#159]
### Behaviour

After pulling the latest version 1.14.0, I'm getting the following error

`Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')`

#### Steps to reproduce this issue

1. Use the latest version, 1.14.0
2. `Error: Fail to load docker/login-action/v1/action.yml`

#### Expected behaviour

> It should load the action

#### Actual behaviour

> It throws an error while loading the action

### Logs

```
Download action repository 'docker/login-action@v1' (*******)
Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node16' is not supported, use 'docker' or 'node12' instead.')
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load docker/login-action/v1/action.yml
```

**Comment by shanlashari** [comment]
+1

**Comment by peterzernia** [comment]
Downgrading to v1.13.0 resolves the issue e.g.

`uses: docker/login-action@v1.13.0`

**Comment by crazy-max** [comment]
Can someone post his workflow please? Thx.

**Comment by BenV** [comment]
For us yes, this is a self hosted runner on GHE and we were caught off guard because we were pinned to @v1, pinning to 1.13.0 resolves the issue, but maybe this should be a major version bump?

**Comment by crazy-max** [comment]
@BenV Which version of self-hosted runner? Node 16 is available since [v2.285.0](https://github.com/actions/runner/releases/tag/v2.285.0) (29 Nov 2021). Friendly ping @TingluoHuang just in case it's something else than an outdated runner.

**Comment by BenV** [comment]
@crazy-max Looks like 2.283.3 (Oct 04, 2021) - fairly old, but not ancient (IMO)

**Comment by crazy-max** [comment]
@BenV fwiw, Node 12 is EOL on April 30, 2022.

**Comment by BenV** [comment]
@crazy-max Sure, I'm just a consumer of this stuff at a corporation (which is the position I'm sure many others are in on GHE) - this has started a conversation about version/SHA pinning for our actions which is certainly a good thing in the long run, and hopefully anyone who runs into this problem will be able to find this workaround easily enough, just wanted to provide the information. Thanks for looking into it!

**Comment by crazy-max** [comment]
@BenV Oh sure I don't blame anyone but I was thinking runner had an auto-update feature?

**Comment by BenV** [comment]
@crazy-max No idea to be honest, I will certainly ask. I would not be surprised if they were disabled. Thanks again!

**Comment by justfalter** [comment]
The latest stable release of Github Enterprise Server 3.3.4  ships with actions runner 2.283.3. I know I don't have `--disableupdate` within my environment, and 2.283.3 is the latest version that GHE will upgrade to on our runners.

**Comment by jwo** [comment]
We are on github enterprise, on prem, and are running 2.279.0 

We saw the errors, and downgrading to force 1.13 appears to fix for us.

**Comment by justfalter** [comment]
Node 16 support won't be available to GHE until 3.4, which is still in RC: https://docs.github.com/en/enterprise-server@3.4/admin/release-notes#3.4.0.rc1 ... I'm uncertain as to whether it is simply a matter of upgrading to a newer version of the actions runner... There seems to be a tight coupling of the actions runner version and the GHE version.

Really, this feels like a breaking change for GHE users.

**Comment by crazy-max** [comment]
> Node 16 support won't be available to GHE until 3.4, which is still in RC: https://docs.github.com/en/enterprise-server@3.4/admin/release-notes#3.4.0.rc1 ... I'm uncertain as to whether it is simply a matter of upgrading to a newer version of the actions runner... There seems to be a tight coupling of the actions runner version and the GHE version.
> 
> Really, this feels like a breaking change for GHE users.

@justfalter Thanks a lot for your feedback! I will move the mutable `v1` tag to the previous release in the meantime and keep an eye on GHE.

**Comment by crazy-max** [comment]
`v1` tag is now `v1.13.0`.

**Comment by justfalter** [comment]
@crazy-max Keep in mind that not everyone will be immediately upgrading to GHE 3.4 once it is released. Enterprises can be slow-moving. 

I don't know if GHA provides any telemetry for what version of GHE is leveraging your actions, but this seems like an excellent use case for such information.

**Comment by crazy-max** [comment]
@justfalter https://github.com/actions/checkout/pull/689 :eyes:
