### ISSUE TITLE
Docker is unable to access Github registry during action in self-hosted runner

### ISSUE THREAD

**Issue by hjokunbus** [docker/login-action#262]
#### Steps to reproduce this issue

1. Create personal token
2. Deploy token with repository
3. Trigger action

#### Expected behaviour

> During "Starting job container" Docker logs into ghcr.io and syncs container before next step

#### Actual behaviour
```
##[debug]Evaluating condition for step: 'Initialize containers'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Initialize containers
##[debug]Register post job cleanup for stopping/deleting containers.
Checking docker version
  /usr/bin/docker version --format '{{.Server.APIVersion}}'
  '1.39'
  Docker daemon API version: '1.39'
  /usr/bin/docker version --format '{{.Client.APIVersion}}'
  '1.39'
  Docker client API version: '1.39'
Clean up resources from previous jobs
  /usr/bin/docker ps --all --quiet --no-trunc --filter "label=82336b"
  /usr/bin/docker network prune --force --filter "label=82336b"
Create local container network
  /usr/bin/docker network create --label 82336b github_network_680e367e3ca74e168b62ad703860f04f
  c338b7456f973cc0cba2cff9a77691bb7d90bb85c7022adcf60a88592397fa7b
Starting job container
  /usr/bin/docker --config /home/holger/actions-runner/_work/_temp/.docker_e54ffea8-e56e-460e-867a-bc788bd55961 login ghcr.io -u hjokunbus --password-stdin
  Error: Docker login for 'ghcr.io' failed with exit code 1
  ##[debug]System.InvalidOperationException: Docker login for 'ghcr.io' failed with exit code 1
  ##[debug]   at GitHub.Runner.Worker.ContainerOperationProvider.ContainerRegistryLogin(IExecutionContext executionContext, ContainerInfo container)
  ##[debug]   at GitHub.Runner.Worker.ContainerOperationProvider.StartContainerAsync(IExecutionContext executionContext, ContainerInfo container)
  ##[debug]   at GitHub.Runner.Worker.ContainerOperationProvider.StartContainersAsync(IExecutionContext executionContext, Object data)
  ##[debug]   at GitHub.Runner.Worker.JobExtensionRunner.RunAsync()
  ##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
  ##[debug]Finishing: Initialize containers
```

This broke at August 26th while working just fine before. The secret has not expired and also still works for manual login into ghcr.io. Only the action fails to perform. Re-runs of previously successful actions fail, as well.

Please note that there already is a feedback about this in the [GitHub community](https://github.com/orgs/community/discussions/30753) that for the last days nobody had responded to.

### Configuration

```yml
name: Clang-Tidy docker runner

on: [push]

jobs:
    test:
        name: Run static code analysis
        runs-on: [self-hosted, tests-only]
        container:
            image: ghcr.io/revolutionpi/clang-tidy-analysis:0.3
            credentials:
                username: ${{ github.actor }}
                password: ${{ secrets.CONTAINER_READ }}
        steps:

        # workaround github runner environment pollution
        - name: Clean the workspace
          run: rm -rf $GITHUB_WORKSPACE/*
 
        - uses: actions/checkout@v3
          with:
            submodules: recursive

        - name: Test with clang-tidy
          run: clang-tidy src/*.c src/*.h -- -IpiControl -std=c99
```

### Logs

[logs_65.zip](https://github.com/docker/login-action/files/9444765/logs_65.zip)

**Comment by crazy-max** [comment]
Seems to have been a partial disruption of GitHub registry: https://github.com/orgs/community/discussions/30753#discussioncomment-3587506

Closing this issue since that should answer your question, but feel free to re-open if it doesn't. Thanks.

**Comment by hjokunbus** [comment]
> Seems to have been a partial disruption of GitHub registry: https://github.com/orgs/community/discussions/30753#discussioncomment-3587506
> 
> Closing this issue since that should answer your question, but feel free to re-open if it doesn't. Thanks.

The original problem still occurs on our end. And it occurs for weeks now, not just hours. @crazy-max So you want me to post the same issue again? Because I cannot reopen an issue that you've closed myself.

**Comment by crazy-max** [comment]
@hjokunbus Don't see any use of our `docker/login-action` in your workflow or logs.

**Comment by hjokunbus** [comment]
@crazy-max Interesting. What other than "docker login" fails during my actions then? The [ContainerOperationProvider.cs](https://github.com/actions/runner/blob/main/src/Runner.Worker/ContainerOperationProvider.cs) in the log is part of your GitHub Action. Or isn't it? Can you point me to the responsible project, if you think that it has nothing to do with docker login?

**Comment by crazy-max** [comment]
I don't know. This repository is about the `docker login` action (see [README](https://github.com/docker/login-action#about)). Not `docker login` command by itself.

> The [ContainerOperationProvider.cs](https://github.com/actions/runner/blob/main/src/Runner.Worker/ContainerOperationProvider.cs) in the log is part of your GitHub Action.

It's part of the runner application. Suggest to open an issue on https://github.com/actions/runner
