### ISSUE TITLE
Deprecated Docker V1 version. 

### ISSUE THREAD

**Issue by azarudeena** [docker/login-action#273]
### Behaviour

Now docker has deprecated the v1 version on docker APIs. Can we please upgrade the login action to use the V2 APIs to login? or is it dependant on the the underlying docker engine in the system?

**Comment by crazy-max** [comment]
> Now docker has deprecated the v1 version

Deprecation is only about the [Docker Hub API v1](https://www.docker.com/blog/docker-hub-v1-api-deprecation/) and is not related to the login command.

[`docker login` sends a POST request](https://github.com/docker/cli/blob/e97d5d54c3519d5653fd6a131e35cc0fe988ed54/vendor/github.com/docker/docker/client/login.go#L15) to Docker Engine at [`/auth` endpoint](https://docs.docker.com/engine/api/v1.41/#tag/System/operation/SystemAuth).
