### ISSUE TITLE
Usage for harbor is not an option

### ISSUE THREAD

**Issue by buggsdummy** [docker/login-action#300]
https://goharbor.io

There isn't a custom way to push outside of what's existing, I'd like to request that harbor be added as one of the login options. 

These are the only things we can push to. Thanks! 

Usage is for the following only listed in the notes

**Comment by crazy-max** [comment]
@buggsdummy Looking at [their docs](https://goharbor.io/docs/1.10/working-with-projects/working-with-images/pulling-pushing-images/#pulling-images), it doesn't seem anything special is required to login to this registry:

> ```
> docker login <harbor_address>
> ```

So should work just fine by setting the right values for [`registry`, `login` and `password` inputs](https://github.com/docker/login-action#inputs).
