### ISSUE TITLE
Using private ECR images as a Service in Github Actions

### ISSUE THREAD

**Issue by BeyondEvil** [docker/login-action#317]
If you come here looking for a way to use private ECR images as ["services"](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservices) in Github Actions workflows, here's a workaround:

https://github.com/community/community/discussions/19819#discussioncomment-3969355

**Comment by BeyondEvil** [comment]
I'll leave this open for maintainers to acknowledge and potentially add labels to. Then please feel free to close. 🙏

**Comment by crazy-max** [comment]
Don't think this is related to this action but GitHub services containers documentation: https://docs.github.com/en/actions/using-containerized-services/about-service-containers
