### ISSUE TITLE
Login persistence on next action steps

### ISSUE THREAD

**Issue by fagiani** [docker/login-action#34]
Hi, I am using a step after using `docker/login-action@v1` called `mamezou-tech/buildpacks-action@master` and as they use a Dockerfile to run the step the docker connection session is not persisted.

Is there a way to make it work? What could be done to have other "dockerized" steps to be able to benefit from the docker login action?

Thanks!

**Comment by crazy-max** [comment]
@fagiani 

> Is there a way to make it work? What could be done to have other "dockerized" steps to be able to benefit from the docker login action?

As explained in https://github.com/docker/login-action/issues/32#issuecomment-730079570 you just have to set the env var `DOCKER_CONFIG: $HOME/.docker` in your workflow and docker config should be propagated to the `mamezou-tech/buildpacks-action` which uses a [dind conainer](https://github.com/mamezou-tech/buildpacks-action/blob/62a5f1cb41e5c6bada1cdac00cb159c7b1adc8f1/Dockerfile#L1) under the hood. See also https://github.com/crazy-max/docker-login-action/blob/6d86f4308bf70c7651412d9883845a2dcc1d0c83/.github/workflows/ci.yml#L12-L32 as a live example.
