### ISSUE TITLE
supporting AWS public registry: public.ecr.aws

### ISSUE THREAD

**Issue by vincentsarago** [docker/login-action#36]
This is not a bug repport but maybe more a documentation request so please feel free to close it if there is a better place to raise this. And because I'm far to be an expert, I maybe totally wrong!

The public AWS repository (public.ecr.aws) needs almost the same login process as the private ECR but there is a huge difference in the registry URL which make it not compatible with this action

```
aws ecr-public get-login-password --region {region} | docker login --username AWS --password-stdin public.ecr.aws/{user_registry_name}
```

there are 2 problems with the public registry url:
1. there is no `amazonaws` in the registery name, so: 

https://github.com/docker/login-action/blob/12fd63324cffe50514ebf0acd23eb936f0a59204/src/aws.ts#L5-L7

isn't triggered 

2. there is no `region` in the registry url, so: 

https://github.com/docker/login-action/blob/12fd63324cffe50514ebf0acd23eb936f0a59204/src/aws.ts#L9-L11

won't work as well.

I see a blocker for a region, but this could be resolved if the user uses the `Configure AWS Credentials action`

Edit:
well there is a third point

3. the aws cli sub command is `ecr-public` not `ecr` 🤦

**Comment by crazy-max** [comment]
@vincentsarago Thanks for your feedback I will take a look at adding support to this registry.

**Comment by vincentsarago** [comment]
Also FYI, you'll need `aws-sdk>=2.806.0`https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#28060 which is not the one provided by `aws-actions/configure-aws-credentials@v1` yet (maybe in couple days I guess)
