### ISSUE TITLE
secrets not passing

### ISSUE THREAD

**Issue by bash-stack** [docker/login-action#57]
### Behaviour
tried everything ( did a non-fork public clone)

```githubgetsworseandevenmarkdownparseriscrapped

      - name: Prepare
        id: prep
          super_secret: ${{ secrets.DOCKER_ORG }}
          docker_user: ${{ secrets.DOCKER_USERNAME }}
          docker_repo: ${{ secrets.DOCKER_REPO }}
          docker_org: ${{ secrets.DOCKER_ORG }}
          foolingia: ${{ secrets.DOCKER_USERNAME }}
          
        run: |
          echo "$FOOLONGIA" > /tmp/file
          base64 -w0 /tmp/file
          echo "supersec: $SUPER_SECRET"
          #DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/${GITHUB_REPOSITORY#*/}
          DOCKER_IMAGE=${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPO }}
          VERSION=latest
          SHORTREF=${GITHUB_SHA::8}
          echo "$DOCKER_IMAGE"
          echo base64
          echo "$DOCKER_IMAGE"|base64 -w0
       
       name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

```

RESULT:

```

base64 -w0 /tmp/file
  DOCKER_IMAGE=${DOCKER_ORG}/${DOCKER_REPO}
  
  echo "supersec: $SUPER_SECRET"
  #DOCKER_IMAGE=***/${GITHUB_REPOSITORY#*/}
  VERSION=latest
  SHORTREF=${GITHUB_SHA::8}
  echo "$DOCKER_IMAGE"
  echo base64
  echo "$DOCKER_IMAGE"|base64 -w0
  shell: /usr/bin/bash -e {0}
  env:
    super_secret: ***
    docker_user: ***
    docker_repo: ***
    docker_org: ***
    foolingia: ***
Cg==supersec: 
/
base64
Lwo=


Run docker/login-action@v1
Error: Username and password required
```

in other repos it works ...

really annyoing ,maybe github issue itself , but about to switch away from sh*thub since microsoft crapped it up.. completely unusable mess since in gitlab you can at least switch off that secret replacing clowns-party for debugging ..

**Comment by crazy-max** [comment]
@bash-stack 

> `Error: Username and password required`

`secrets.DOCKER_USERNAME` and/or `secrets.DOCKER_TOKEN` secrets are empty.  See also https://github.com/docker/login-action/issues/54#issuecomment-774504364

**Comment by bash-stack** [comment]
nope , it was not ( also tried auxilliary stuff, using environment and repo secret)

it turned out to be ( hold your breath) :

sh*thub replaced every `VARIABLE VALUE` with `***` 
(  e.g. the docke-username  was used in the image tag , but the REAL result was `***/REPO-TAG`
so the ( ugly) solution was :  
* fill out all the parts that contain possibly replaced strings in .yml 
* leave only DOCKER_PASSWORD (or _TOKEN, you name it ) in the .yml
* see that your token is not replaced by **** ( e.g. you password is not the repo-name or user name , should be okay in most cases)
* build happily

( and think , oh sh*thub , thanks for stealing 2,5 hours , thats maybe the time saved by faster CI-Builds vs gitlab , but in gitlab i can at least debug what is going on without provoding and intercepting runners , all hail microsoft )
