### ISSUE TITLE
 It always fails While logining local-deployment Nexus

### ISSUE THREAD

**Issue by axiao-crud** [docker/login-action#586]
I met a phenomenon.

1.deploy nexus in localhost:8081 like this
![image](https://github.com/docker/login-action/assets/98532074/bb24b650-5905-4367-9c11-0bd69a665df3)

2.create a docker repository and config
![image](https://github.com/docker/login-action/assets/98532074/0b18a590-ca16-4833-952a-c539e59cc6a9)

3.config docker registry and restart
"insecure-registries": [
    "127.0.0.1:8082"
  ]

4.then try input in cmd
$ docker login 127.0.0.1

get a response like this :
Error response from daemon: Get "http://127.0.0.1:8082/v2/": dial tcp 127.0.0.1:8082: connect: connection refused

i click thr url "http://127.0.0.1:8082/v2/" and get a response like this; 

{
  "errors": [
    {
      "code": "UNAUTHORIZED",
      "message": "access to the requested resource is not authorized",
      "detail": null
    }
  ]
}

Result:
I have already solved this question by modifing the ip 127.0.0.1 to my actual IPV4 address .

Does Anyone knows Why？
Is it useful to analyze this issue using wireshark？

**Comment by crazy-max** [comment]
Works fine in our e2e tests with Nexus: https://github.com/docker/build-push-action/actions/runs/6156437652/job/16705112653#step:10:35

![image](https://github.com/docker/login-action/assets/1951866/2c07decf-96f2-49ff-9f71-2b1599134d40)

Closing as this does not seem to be an issue with the action but registry's configuration.
