### ISSUE TITLE
Support login via Direct Workload Identity Federation

### ISSUE THREAD

**Issue by cbini** [docker/login-action#640]
### Description

v2 of the Google auth action allows for "direct" WIF, which drops the intermediate dependency of needing a service account. However, there doesn't appear to be a way to pass the credentials file or auth token it generates to the login action.

https://github.com/google-github-actions/auth#direct-wif

**Comment by bjornherder** [comment]
It is possible by adding the argument  `token_format: "access_token"` to the `google-github-actions/auth@v2` action. Here is a [link to the docs](https://github.com/google-github-actions/auth?tab=readme-ov-file#inputs-generating-oauth-20-access-tokens).

The access token can then be supplied through the password argument, i.e. `password: "${{ steps.auth.outputs.access_token }}"`

**Comment by cbini** [comment]
> This works for me.
> 
> ```yaml
> - uses: google-github-actions/auth@v2
>   with:
>     project_id: ...
>     workload_identity_provider: ...
> - run: gcloud auth configure-docker ${{ secrets.MY_REGISTRY }}
> ```

Thanks for this! Figured I could use the Docker login action, but I'll give this a try.

**Comment by cbini** [comment]
@mozisan do you have a full workflow example you could share? I'm trying `gcloud auth configure-docker`, but the `docker/build-push-action` is still failing with:

```
ERROR: failed to push us-central1-docker.pkg.dev/.../.../...: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://us-central1-docker.pkg.dev/v2/token?scope=repository%3A...%2F...%2F...%3Apull%2Cpush&service=us-central1-docker.pkg.dev: 403 Forbidden
```
(my repo-specific info removed)

**Comment by cbini** [comment]
Closing, as I no longer use this action after this resolution. Not sure if there's a way to integrate using the gcloud credHelper into the action, but maybe it could be helpful in the future.

**Comment by JordanP** [comment]
`google-github-actions/auth@v2` is a pretty heavy action. It would be great to have a solution using only this `docker/login-action`. AFAIK the solution provided [here](https://github.com/docker/login-action/issues/640#issuecomment-1857777053) does not use Direct WIF but use [Workload Identity Federation through a Service Account](https://github.com/google-github-actions/auth?tab=readme-ov-file#indirect-wif).

**Comment by JordanP** [comment]
Actually it is supported. See [here](https://github.com/actions/starter-workflows/blob/1394e47812550adc70e4af1b714a8000ceee6c00/deployments/google-cloudrun-docker.yml#L60-L73) for a working example.
