### ISSUE TITLE
CR_PAT for GitHub Container Registry

### ISSUE THREAD

**Issue by dschinkel** [docker/login-action#8]
Is the `CR_PAT` the GitHub Container Registry Personal Access Token?  Can we update the docs to explain exactly what this is?  I forget where you even generate that from.

**Comment by crazy-max** [comment]
@dschinkel 

> Is the CR_PAT the Google Cloud Run Personal Access Token?

This is explained in the README [here](https://github.com/docker/login-action#github-container-registry).

**Comment by dschinkel** [comment]
I see it now sorry.  My head is spinning from looking at Cloud Docs and GitHub Docs for a week now.  Thx.

**Comment by crazy-max** [comment]
@dschinkel 

> Sounds like your github action here for Github Container Repository is only able to use an access token and not secrets.GITHUB_TOKEN yet?

See https://twitter.com/clarkbw/status/1300853015113396225
