### ISSUE TITLE
Error: Username and password required

### ISSUE THREAD

**Issue by JamesArthurHolland** [docker/login-action#90]
- name: Log in to Docker Hub
   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
     with:
        username: ${{ env.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}

It breaks with error:

Run docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
  with:
    username: correctUsername
    logout: true
  env:
    DOCKERHUB_PASS: 
    DOCKERHUB_USER: ozone2021
Error: Username and password required

The secret for password exists I think. It's added as an environment secret. Should it be asterisks if it exists?

**Comment by fwanghe** [comment]
can I ask how did you fix the problem please? @JamesArthurHolland
