### ISSUE TITLE
Error to login in mac-os action

### ISSUE THREAD

**Issue by wirwolf** [docker/login-action#93]
Output log:
```
Run docker/login-action@v1
  with:
    username: ***
    password: ***
    logout: true
Logging into Docker Hub...
Error: Unable to locate executable file: docker. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

```
log link: https://github.com/rundax/go-bitsong/runs/3341040866?check_suite_focus=true
config file: https://github.com/rundax/go-bitsong/blob/develop/.github/workflows/build.yml

**Comment by crazy-max** [comment]
Docker is not available on MacOS GitHub Runners: https://github.com/actions/virtual-environments/
